spring.application.name=gateway-service
server.port=8000

spring.main.web-application-type=reactive

# Eureka Configuration
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.codec.max-in-memory-size=10MB

# JWT Secret Key
jwt.secret-key=${SECRET_KEY}

# Gateway Global Configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Profile Service Routes
spring.cloud.gateway.routes[0].id=profile-service
spring.cloud.gateway.routes[0].uri=lb://profile-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/profile-service/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/profile-service/(?<segment>.*), /$\{segment}

# Product Service Routes
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/product-service/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/product-service/(?<segment>.*), /$\{segment}

# Cart Service Routes
spring.cloud.gateway.routes[2].id=cart-service
spring.cloud.gateway.routes[2].uri=lb://cart-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/cart-service/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/cart-service/(?<segment>.*), /$\{segment}


# Image Service Routes
spring.cloud.gateway.routes[3].id=image-service
spring.cloud.gateway.routes[3].uri=lb://image-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/image-service/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/image-service/(?<segment>.*), /$\{segment}

# Circuit Breaker Configuration
#spring.cloud.circuitbreaker.resilience4j.enabled=true